'use strict';
const $=id=>document.getElementById(id);
let items=[],sha=null,connected=false,busy=false,currentSvg='',currentId='',dirty=false;
const settings=['owner','repo','branch','base'];
try{const saved=JSON.parse(localStorage.getItem('qr-settings')||'{}');settings.forEach(k=>{if(saved[k])$(k).value=saved[k]});items=validate(JSON.parse(localStorage.getItem(draftKey())||'{"items":[]}')).items;if(items.length){dirty=true;$('dirty').textContent='已還原本機草稿';status('已還原本機資料。連線讀取前請先備份尚未發布的變更。')}}catch{status('本機資料無法讀取，請匯入備份。',true)}
function status(t,error=false){$('status').textContent=t;$('status').className=error?'error':''}
function validUrl(value){const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('目的網址只接受 http/https，不能包含帳號密碼。');return u.href}
function validate(data){if(!data||!Array.isArray(data.items)||data.items.length>2000)throw Error('清單格式錯誤或超過 2,000 組。');const ids=new Set();return {...data,items:data.items.map(x=>{if(!x||typeof x.id!=='string'||!/^[a-zA-Z0-9_-]{1,64}$/.test(x.id)||ids.has(x.id))throw Error('編號格式錯誤或重複。');ids.add(x.id);if(typeof x.name!=='string'||typeof x.url!=='string')throw Error('名稱與網址格式錯誤。');if(x.url)validUrl(x.url);return {id:x.id,name:x.name.slice(0,200),url:x.url,enabled:x.enabled!==false};})}}
function config(){const c=Object.fromEntries(settings.map(k=>[k,$(k).value.trim()]));if(!/^[\w-]+$/.test(c.owner)||!/^[\w.-]+$/.test(c.repo)||!c.branch)throw Error('請填入 GitHub 帳號、儲存庫及分支。');c.base=validUrl(c.base);const u=new URL(c.base);if(u.search||u.hash)throw Error('Pages 網址不能含查詢參數或 #。');c.base=c.base.replace(/\/?$/,'/');return c}
function draftKey(){return 'qr-draft:'+settings.slice(0,3).map(k=>$(k).value.trim()).join('/')}
function saveSettings(){localStorage.setItem('qr-settings',JSON.stringify(Object.fromEntries(settings.map(k=>[k,$(k).value.trim()]))))}
function save(){dirty=true;$('dirty').textContent='尚未發布';try{localStorage.setItem(draftKey(),JSON.stringify({version:1,items}));saveSettings()}catch{status('無法保存本機草稿，請先下載備份。',true)}}
function render(){const query=$('search').value.toLowerCase();$('list').replaceChildren();$('count').textContent=items.length+' 組';for(const item of items.filter(x=>(x.id+' '+x.name+' '+x.url).toLowerCase().includes(query))){const row=document.createElement('div');row.className='row';const id=document.createElement('div');id.className='badge';id.textContent=item.id;const caption=document.createElement('small');caption.textContent=item.enabled?(item.url?'已指定':'待指定'):'已停用';id.append(caption);const name=document.createElement('input');name.value=item.name;name.placeholder='名稱';name.setAttribute('aria-label',item.id+' 名稱');name.onchange=()=>{item.name=name.value;save()};const target=document.createElement('input');target.className='target';target.value=item.url;target.placeholder='https://…（可留空）';target.setAttribute('aria-label',item.id+' 目的網址');target.onchange=()=>{item.url=target.value.trim();save();caption.textContent=item.enabled?(item.url?'已指定':'待指定'):'已停用'};const actions=document.createElement('div');actions.className='row-actions actions';const qr=document.createElement('button');qr.textContent='QR';qr.onclick=()=>guard(()=>showQr(item));const toggle=document.createElement('button');toggle.className='secondary';toggle.textContent=item.enabled?'停用':'啟用';toggle.onclick=()=>{item.enabled=!item.enabled;save();render()};actions.append(qr,toggle);row.append(id,name,target,actions);$('list').append(row)}}
function add(n){if(items.length+n>2000)throw Error('最多 2,000 組。');let id=1;for(let i=0;i<n;i++){while(items.some(x=>x.id===String(id).padStart(3,'0')))id++;items.push({id:String(id++).padStart(3,'0'),name:'',url:'',enabled:true})}save();render()}
function qrUrl(item){return new URL('go.html?id='+encodeURIComponent(item.id),config().base).href}
function svgFor(text){const qr=qrcodegen.QrCode.encodeText(text,qrcodegen.QrCode.Ecc.MEDIUM);const size=qr.size+8;let d='';for(let y=0;y<qr.size;y++)for(let x=0;x<qr.size;x++)if(qr.getModule(x,y))d+=`M${x+4},${y+4}h1v1h-1z `;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="1024" height="1024" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/><path d="${d}" fill="black"/></svg>`}
function showQr(item){currentId=item.id;currentSvg=svgFor(qrUrl(item));$('qrTitle').textContent=item.id+' '+item.name;$('qrPreview').innerHTML=currentSvg;$('qrLink').textContent=qrUrl(item);$('qrDialog').showModal()}
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function encode(s){return btoa(Array.from(new TextEncoder().encode(s),b=>String.fromCharCode(b)).join(''))}
function decode(s){return new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)))}
async function api(path,options={}){const token=$('token').value.trim();if(!token)throw Error('請先輸入專用權杖。');const response=await fetch('https://api.github.com'+path,{...options,cache:'no-store',headers:{Accept:'application/vnd.github+json','Authorization':'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(options.body?{'Content-Type':'application/json'}:{})}});if(!response.ok){if(response.status===404)throw Error('找不到儲存庫或 links.json，請先上傳完整專案，並確認權杖範圍。');if(response.status===409||response.status===422)throw Error('版本衝突或分支設定不符。請備份草稿後重新讀取。');throw Error('GitHub 回應 '+response.status+'，請檢查權杖效期與 Contents 權限。')}return response.json()}
function repoPath(c){return '/repos/'+encodeURIComponent(c.owner)+'/'+encodeURIComponent(c.repo)}
async function remote(c){return api(repoPath(c)+'/contents/links.json?ref='+encodeURIComponent(c.branch))}
async function connect(){const c=config();if(dirty&&!confirm('讀取 GitHub 清單會取代本機草稿。是否繼續？'))return;const file=await remote(c);const data=validate(JSON.parse(decode(file.content)));items=data.items;sha=file.sha;connected=true;dirty=false;localStorage.setItem(draftKey(),JSON.stringify(data));saveSettings();$('dirty').textContent='已讀取 GitHub';render();status('已連線。修改後按「發布全部變更」。')}
async function publish(){if(deployment&&JSON.stringify(items)===JSON.stringify(deployment.items)&&JSON.stringify(config())===JSON.stringify(deployment.c)){status('這批資料已存入 GitHub，正在重新確認部署，不會重複提交。');checkDeployment();return}if(!connected)throw Error('請先連線並讀取 GitHub 清單。若有本機草稿，請先備份，讀取後再匯入。');const c=config();const snapshot=validate({version:1,revision:crypto.randomUUID(),items:structuredClone(items)});const before=await remote(c);if(before.sha!==sha)throw Error('GitHub 清單已被其他裝置更新。請先備份草稿，重新讀取後合併。');const response=await api(repoPath(c)+'/contents/links.json',{method:'PUT',body:JSON.stringify({message:'Update QR destinations',branch:c.branch,sha,content:encode(JSON.stringify(snapshot,null,2)+'\n')})});sha=response.content.sha;startDeployment(c,snapshot,response.commit?.sha);}
async function guard(fn){if(busy)return;busy=true;document.querySelectorAll('button,input').forEach(x=>x.disabled=true);try{await fn()}catch(e){status(e.message,true)}finally{busy=false;document.querySelectorAll('button,input').forEach(x=>x.disabled=false)}}
settings.forEach(k=>$(k).addEventListener('change',()=>{connected=false;sha=null;saveSettings();status('設定已變更，請重新連線。')}));
$('connectionForm').addEventListener('submit',e=>{e.preventDefault();guard(connect)});$('publish').onclick=()=>guard(publish);$('add').onclick=()=>guard(()=>add(1));$('batch').onclick=()=>guard(()=>{const n=Number($('batchCount').value);if(!Number.isInteger(n)||n<1||n>200)throw Error('批次數量請填 1–200。');add(n)});$('search').oninput=render;$('lock').onclick=()=>{$('token').value='';status('權杖已清除。')};$('backup').onclick=()=>download('qr-backup.json',JSON.stringify({version:1,items},null,2),'application/json');$('import').onchange=()=>guard(async()=>{const file=$('import').files[0];if(!file)return;if(file.size>2000000)throw Error('備份檔案過大。');const data=validate(JSON.parse(await file.text()));if(!confirm('匯入會取代目前草稿，是否繼續？'))return;items=data.items;save();render();status('已匯入本機草稿，尚未發布。');$('import').value=''});$('download').onclick=()=>download('qr-'+currentId+'.svg',currentSvg,'image/svg+xml');$('closeDialog').onclick=()=>$('qrDialog').close();
$('sheet').onclick=()=>guard(()=>{config();const w=window.open('','_blank');if(!w)throw Error('請允許開啟列印視窗。');w.document.write('<!doctype html><html lang="zh-Hant"><title>QR 列印表</title><style>body{font-family:system-ui}main{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}article{text-align:center;break-inside:avoid;border:1px solid #ddd;padding:12px}svg{width:160px;height:160px}p{overflow-wrap:anywhere;font-size:11px}@media print{button{display:none}}</style><button onclick="print()">列印／另存 PDF</button><main></main></html>');w.document.close();for(const item of items){const card=w.document.createElement('article');card.innerHTML=svgFor(qrUrl(item));const label=w.document.createElement('h3');label.textContent=item.id+' '+item.name;const url=w.document.createElement('p');url.textContent=qrUrl(item);card.append(label,url);w.document.querySelector('main').append(card)}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();$('install').hidden=false;$('install').onclick=async()=>{await e.prompt();$('install').hidden=true}});if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>status('離線功能未啟用，仍可線上使用。'));
function zipSvgs(){const parts=[],central=[];let offset=0;const bytes=s=>new TextEncoder().encode(s);const header=(size)=>{const b=new Uint8Array(size);return [b,new DataView(b.buffer)]};for(const item of items){const name=bytes('qr-'+item.id+'.svg'),data=bytes(svgFor(qrUrl(item)));let crc=0xffffffff;for(const b of data){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}crc=(crc^0xffffffff)>>>0;const [local,l]=header(30);l.setUint32(0,0x04034b50,true);l.setUint16(4,20,true);l.setUint32(14,crc,true);l.setUint32(18,data.length,true);l.setUint32(22,data.length,true);l.setUint16(26,name.length,true);parts.push(local,name,data);const [entry,c]=header(46);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint32(16,crc,true);c.setUint32(20,data.length,true);c.setUint32(24,data.length,true);c.setUint16(28,name.length,true);c.setUint32(42,offset,true);central.push(entry,name);offset+=local.length+name.length+data.length}const centralSize=central.reduce((s,x)=>s+x.length,0);const [end,e]=header(22);e.setUint32(0,0x06054b50,true);e.setUint16(8,items.length,true);e.setUint16(10,items.length,true);e.setUint32(12,centralSize,true);e.setUint32(16,offset,true);download('qr-codes.zip',new Blob([...parts,...central,end]),'application/zip')}
const zipButton=document.createElement('button');zipButton.className='secondary';zipButton.textContent='下載全部 SVG ZIP';zipButton.onclick=()=>guard(()=>{config();zipSvgs()});$('sheet').after(zipButton);
render();
