'use strict';
let deployment=null,deploymentTimer=null,deploymentChecking=false,deploymentGeneration=0;
const deployPanel=document.createElement('section');deployPanel.id='deploymentPanel';deployPanel.hidden=true;deployPanel.innerHTML='<div class="section-head"><h3 id="deploymentTitle">發布狀態</h3><span id="deploymentElapsed"></span></div><ol class="deployment-steps"><li>① 存入 GitHub</li><li>② GitHub Pages 部署</li><li>③ 確認網站版本</li></ol><p id="deploymentDetail" aria-live="polite"></p><div class="actions"><button id="checkDeployment" class="secondary">重新確認狀態</button><a id="deploymentLink" target="_blank" rel="noopener noreferrer">查看 GitHub 部署進度 ↗</a></div>';
document.getElementById('status').after(deployPanel);
function deploymentUI(title,detail,stage,error=false){deployPanel.hidden=false;document.getElementById('deploymentTitle').textContent=title;document.getElementById('deploymentDetail').textContent=detail;deployPanel.dataset.state=error?'error':stage===3?'success':'pending';document.querySelectorAll('.deployment-steps li').forEach((n,i)=>{n.className=i<stage?'complete':i===stage?'active':''});if(deployment)document.getElementById('deploymentElapsed').textContent='已過 '+Math.floor((Date.now()-deployment.started)/1000)+' 秒';}
function startDeployment(c,snapshot,commit){clearTimeout(deploymentTimer);deploymentGeneration++;deployment={c,revision:snapshot.revision,items:snapshot.items,commit,started:Date.now()};localStorage.setItem('qr-pending-deployment',JSON.stringify(deployment));document.getElementById('deploymentLink').href='https://github.com/'+encodeURIComponent(c.owner)+'/'+encodeURIComponent(c.repo)+'/actions';document.getElementById('dirty').textContent='已儲存，等待部署';status('清單已存入 GitHub，正在追蹤部署；不需要再次發布。');deploymentUI('已存入 GitHub','正在確認部署與網站版本…',1);checkDeployment();}
async function checkDeployment(){if(!deployment||deploymentChecking)return;deploymentChecking=true;clearTimeout(deploymentTimer);const current=deployment,generation=deploymentGeneration;const valid=()=>generation===deploymentGeneration&&current===deployment;try{try{const r=await fetch(new URL('links.json?check='+Date.now(),current.c.base),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(r.ok&&(await r.json()).revision===current.revision){if(!valid())return;const changed=JSON.stringify(items)!==JSON.stringify(current.items);dirty=changed;document.getElementById('dirty').textContent=changed?'有新草稿尚未發布':'已發布';deploymentUI('網站已更新 ✓',changed?'上一批發布已完成；目前還有新的本機修改。':'已確認網站提供最新清單，現在可掃描 QR Code 使用。',3);status('發布完成，已確認 Pages 清單更新。');localStorage.removeItem('qr-pending-deployment');deployment=null;return}}catch{/* A network failure is not a deployment failure. */}
if(!valid())return;let failed=false;try{const r=await fetch('https://api.github.com/repos/'+encodeURIComponent(current.c.owner)+'/'+encodeURIComponent(current.c.repo)+'/actions/runs?branch='+encodeURIComponent(current.c.branch)+'&per_page=30',{headers:{Accept:'application/vnd.github+json'},cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error();const data=await r.json();if(!valid())return;const run=data.workflow_runs?.find(x=>x.head_sha===current.commit&&(/pages/i.test(x.name)||x.path?.includes('pages')));if(run){document.getElementById('deploymentLink').href=run.html_url;if(run.status==='completed'&&run.conclusion==='success')deploymentUI('部署完成，等待網站更新','GitHub 部署成功，正在確認網站上的清單版本。',2);else if(run.status==='completed'){failed=true;deploymentUI('部署未成功','GitHub 結果：'+run.conclusion+'。請開啟部署進度查看原因；清單已保存在 GitHub。',1,true);document.getElementById('dirty').textContent='已儲存，部署未成功';}else deploymentUI(run.status==='in_progress'?'GitHub Pages 部署中':'等待 GitHub 部署','GitHub 狀態：'+run.status+'。完成後會繼續確認網站版本。',1);}else deploymentUI('等待 GitHub 部署','尚未找到這次提交的 Pages 工作，會持續確認。',1);}catch{if(valid())deploymentUI('等待確認網站更新','暫時無法讀取部署進度（網路或 GitHub API 限制）。仍會直接檢查網站，不需要擴充權杖權限。',1);}
if(!valid())return;if(Date.now()-current.started>15*60*1000){deploymentUI('已儲存，尚未確認網站更新','已追蹤超過 15 分鐘。可查看 GitHub 部署進度，或按「重新確認狀態」，不必再次發布。',1);return}if(!failed)deploymentTimer=setTimeout(checkDeployment,10000);
}finally{deploymentChecking=false;if(deployment&&generation!==deploymentGeneration)deploymentTimer=setTimeout(checkDeployment,0)}}
document.getElementById('checkDeployment').onclick=()=>{if(deployment){deployment.started=Date.now();checkDeployment()}};
window.addEventListener('load',()=>{try{const saved=JSON.parse(localStorage.getItem('qr-pending-deployment')||'null');if(saved&&saved.c&&saved.revision&&Array.isArray(saved.items)){deployment=saved;deploymentGeneration++;document.getElementById('deploymentLink').href='https://github.com/'+encodeURIComponent(saved.c.owner)+'/'+encodeURIComponent(saved.c.repo)+'/actions';deploymentUI('恢復追蹤上次發布','正在重新確認網站版本。',1);checkDeployment()}}catch{}});
