'use strict';
const letterButton=document.createElement('button');letterButton.textContent='製作感謝回函';letterButton.className='secondary';$('sheet').after(letterButton);
const letterDialog=document.createElement('dialog');letterDialog.id='letterDialog';letterDialog.innerHTML='<h2>製作感謝回函</h2><p class="hint">勾選要寄給客人的貼圖，連結與 QR 使用固定網址，可先寄出再開通。</p><label>搜尋貼圖<input id="letterSearch" placeholder="編號或名稱"></label><div id="letterChoices"></div><p id="letterSelection"></p><label>去背圖檔網址（選填，空白不附此列）<input id="cutoutUrl" type="url" placeholder="https://…"></label><p class="hint">去背圖檔網址僅用於本次回函，不會寫入 GitHub。</p><p id="letterError" role="status"></p><div class="actions"><button id="previewLetter">預覽 A4／輸出 PDF</button><button id="closeLetter" class="secondary">取消</button></div>';
document.body.append(letterDialog);let letterSelection=new Set();
function renderLetterChoices(){const q=$('letterSearch').value.trim().toLowerCase();$('letterChoices').replaceChildren();for(const item of items.filter(x=>(x.id+' '+x.name).toLowerCase().includes(q))){const label=document.createElement('label');label.className='letter-choice';const check=document.createElement('input');check.type='checkbox';check.checked=letterSelection.has(item.id);check.disabled=item.enabled===false;check.value=item.id;check.onchange=()=>{if(check.checked)letterSelection.add(item.id);else letterSelection.delete(item.id);$('letterSelection').textContent='已勾選 '+letterSelection.size+' 組'};const text=document.createElement('span');text.textContent=item.id+' · '+(item.name||'未命名貼圖')+(item.enabled===false?'（已停用）':item.url?'':'（待開通）');label.append(check,text);$('letterChoices').append(label)}$('letterSelection').textContent='已勾選 '+letterSelection.size+' 組'}
letterButton.onclick=()=>{letterSelection=new Set([...letterSelection].filter(id=>items.some(x=>x.id===id&&x.enabled!==false)));$('letterError').textContent='';renderLetterChoices();letterDialog.showModal()};$('closeLetter').onclick=()=>letterDialog.close();$('letterSearch').oninput=renderLetterChoices;
function letterNode(doc,tag,text,className){const n=doc.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n}
function buildLetter(doc,selected,cutout){const cards=selected.map(x=>({title:x.name||'專屬貼圖 '+x.id,id:x.id,url:qrUrl(x)}));if(cutout)cards.push({title:'原始去背圖檔（選購）',id:null,url:cutout});const pageCount=Math.ceil(cards.length/3);for(let page=0;page<pageCount;page++){const sheet=letterNode(doc,'section',undefined,'letter-page');const top=letterNode(doc,'div',"AINO'S DAD · MADE FOR YOU",'brand');sheet.append(top,letterNode(doc,'div','✿','letter-flower'),letterNode(doc,'h1',page===0?'謝謝您，讓可愛成為日常。':'您的專屬下載連結（續）'));if(page===0){sheet.append(letterNode(doc,'p','親愛的顧客，您好：'),letterNode(doc,'p',"非常感謝您選擇 Aino's dad 專屬客製化貼圖服務！您的專屬貼圖已完成繪製，並通過 LINE 官方審核上架囉！"));}sheet.append(letterNode(doc,'div','取貨後若無法開啟，請記得私訊我開通。','callout'));for(const card of cards.slice(page*3,page*3+3)){const row=letterNode(doc,'section',undefined,'download-card');const info=letterNode(doc,'div',undefined,'card-info');info.append(letterNode(doc,'h2',card.title));if(card.id)info.append(letterNode(doc,'p','QR 編號：'+card.id,'qr-number'));info.append(letterNode(doc,'p',card.id?'掃描右側 QR Code，或開啟以下網址：':'掃描右側 QR Code，下載並備份您的圖檔：'));const a=letterNode(doc,'a',card.url);a.href=card.url;info.append(a);const qr=letterNode(doc,'div',undefined,'letter-qr');qr.innerHTML=svgFor(card.url);row.append(info,qr);sheet.append(row)}if(page===pageCount-1){const notes=letterNode(doc,'section',undefined,'letter-notes');notes.append(letterNode(doc,'h2','下載小提醒'),letterNode(doc,'p','LINE 貼圖下載仍需自行支付平台顯示的費用，請依購買頁面的說明操作。'));if(cutout)notes.append(letterNode(doc,'p','您選購的原始去背圖檔已附於本回函，請記得下載並另外備份。'));notes.append(letterNode(doc,'p','如果您滿意本次作品，誠摯邀請您給予五星好評與曬圖分享，這對我是莫大的肯定與鼓勵！'));sheet.append(notes,letterNode(doc,'p','未來若有萌寵、寶寶或節慶送禮需求，歡迎隨時再次光臨！祝您使用愉快、天天好心情！','closing'),letterNode(doc,'div',"Aino's dad 敬上",'sign'));}sheet.append(letterNode(doc,'footer',`${page+1} / ${pageCount}`));doc.querySelector('#letterPages').append(sheet)}}
$('previewLetter').onclick=()=>{try{const selected=items.filter(x=>letterSelection.has(x.id)&&x.enabled!==false);if(!selected.length)throw Error('請至少勾選一組貼圖。');config();const cutout=$('cutoutUrl').value.trim();if(cutout)validUrl(cutout);const w=window.open('','_blank');if(!w)throw Error('請允許開啟預覽視窗。');w.document.write('<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>感謝回函</title></head><body><nav><button onclick="print()">列印／另存 PDF</button><span>請選「另存為 PDF」、A4、縮放 100%，並關閉頁首及頁尾。</span></nav><main id="letterPages"></main></body></html>');w.document.close();const css=w.document.createElement('link');css.rel='stylesheet';css.href=new URL('letter.css',location.href).href;w.document.head.append(css);buildLetter(w.document,selected,cutout);$('letterError').textContent='';}catch(e){$('letterError').textContent=e.message}};
